import type React from "react"
import "./globals.css"

export const metadata = {
  title: "Create Project",
  description: "Generated by create.xyz",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fr">
      <body>{children}</body>
    </html>
  )
}
